### ISSUE TITLE
Move to new server (by BlueT)

### ISSUE THREAD

**Issue by CarolHsu** [CarolHsu/rumor-checker#14]
According to @BlueT, there's one more thing to do...

1. Dockerize (?)
2. Deploy pipeline
3. multi-env

**Comment by bluet** [comment]
any updates? :-)

**Comment by CarolHsu** [comment]
@BlueT hahaha, pending still. I'll start with this when I got any chance 😅

**Comment by bluet** [comment]
@CarolHsu till on ToDo or....? XD
