### ISSUE TITLE
Only respond to to "含有不實訊息" message

### ISSUE THREAD

**Issue by vansonlin** [CarolHsu/rumor-checker#16]
Right now the bot responds whatever matches with the rumorbase. 
For example, 

User: "這是台灣路口交通即時畫面，非常好用唷。 "
Robot: "不在查證範圍，即時影像監視器，訊息與謠言查證無關。"
https://cofacts.g0v.tw/article/2rl6ef5574s5a

screenshot: https://imgur.com/a/vRQefXo

Prompting the users with not-helpful messages can be considered as spams, and increase the chances that the bot gets removed from groups by annoyed users. We should only prompt response to message with real rumor.

**Comment by CarolHsu** [comment]
@vansonlin thanks for the suggestion, makes sense to me 👌

**Comment by amber0919** [comment]
![1_Peq_pJdnudWUY19gElkvwg](https://user-images.githubusercontent.com/52592056/60752178-04551700-9ff5-11e9-9dc2-2db57f6b18d7.png)
