### ISSUE TITLE
測試字串是否美玉姨還在正常工作中

### ISSUE THREAD

**Issue by tomohung** [CarolHsu/rumor-checker#5]
參考 https://github.com/CarolHsu/rumor-checker/pull/1#issuecomment-450043816

1. 特定字串讓美玉姨可以不透過cofacts就回應，知道美玉姨還在工作中
2. 避免和一般對話塞車，獨立的priority queue回應 (不確定heroku有沒有限制)

**Comment by CarolHsu** [comment]
`@美玉姨 status` 你覺得怎麼樣

**Comment by tomohung** [comment]
我本來是想 `@美玉姨 早安你好`，不過以美玉姨的媽意見為主

**Comment by CarolHsu** [comment]
@tomohung 這樣我好像變婆等級了
我覺得你的好像比較適合人類，好喔 👍

**Comment by CarolHsu** [comment]
@tomohung heroku 限制 workers 數，好像有一個 dyno 和 workers 的計算機 (?)
http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/

**Comment by tomohung** [comment]
我現在又有另外的想法，也許這些功能不需要
1. 美玉姨是建立在cofacts上，任何和cofacts無關的功能，其實都不是必要的
2. 盡量把<del>責任</del> requests推到confacts上

所以我決定把這個issue關掉
